[build]
command = "npm run build --prefix inventario-vue && mkdir -p public && cp index.html public/ && cp .nojekyll public/ && cp -r assets public/ && cp -r light public/ && cp -r completa public/"
publish = "public"
